site layout
htmlacademy-htmlcss/2066843-device-34 pull request #2
Opened 2022-05-21 13:26 UTC by Aero385

2022-05-29 06:59 UTC, ademaro commented on catalog.html
> +      <img class="search-image" width="16" height="16" src="images/search.svg">
это декоративное изображение, убираем из разметки

2022-05-29 07:00 UTC, ademaro commented on catalog.html
> +      <input type="text" placeholder="Текст поиска" name="текст поиска"/>
type=search

2022-05-29 07:00 UTC, ademaro commented on catalog.html
> +        <img class="user-login" src="images/login.svg" width="13" height="12" alt="login">
декоративное изображение

2022-05-29 07:00 UTC, ademaro commented on catalog.html
> +      </form>
это не форма

2022-05-29 07:00 UTC, ademaro commented on catalog.html
> +      </form>
и это не форма (ссылка)
busket -> basket

2022-05-29 07:01 UTC, ademaro commented on catalog.html
> +      <form class="open-catalog-form">
и тут, конечно, не форма)

2022-05-29 07:02 UTC, ademaro commented on catalog.html
> +        </a>
посмотри материал чем отличаются контентные от декоративных изображений

2022-05-29 07:03 UTC, ademaro requested changes
Нужны правки в разметке, давай созвонимся, что бы обсудить подробнее

2022-05-30 15:28 UTC, Aero385 commented
да конечно , в любой день если воомжно после 18.00 )

2022-06-01 15:33 UTC, ademaro commented on .editorconfig
> +indent_size = 4
тут не надо править, мы работаем в текущем проекте с настройками от «наших заказчиков») Так что давай обратно поменяем..

2022-06-01 15:33 UTC, ademaro commented on Readme.md
> +* Наставник: `Антон Попов`(https://htmlacademy.ru/profile/id78239).
`[Антон Попов](https://htmlacademy.ru/profile/id78239)` не даётся ссылка?)) Вот правильный формат для ссылки в маркдауне

2022-06-01 15:35 UTC, ademaro commented on styles/styles.css
> +    font-family: "Rubik", sans-serif;
нужно указать альтернативный веб-безопасный шрифт

2022-06-01 15:36 UTC, ademaro commented on styles/styles.css
> +.main-navigation-link,  .button-products-list{
лучше разбить на несколько строк

2022-06-01 15:37 UTC, ademaro approved these changes
Давай пока закрою, жду на консультацию)

2022-06-01 15:40 UTC, merged